name: CustomizableSilkTouch
version: '${project.version}'
main: com.ashkiano.customizablesilktouch.CustomizableSilkTouch
api-version: '1.20'
authors: [ AshKiano, BitByLogic ]
commands:
  customizablesilktouch:
    aliases: [ "cst" ]
