# Whether to show the donation request message in the server console on plugin startup.
# The message encourages server administrators to make a donation to support the development at: https://donate.ashkiano.com
# Set to true to display the message in the console, set to false to hide it.
Show-Donate-Message: true

# The permission required for a player to use the customisable silk touch.
# Default is "customizablesilktouch.use".
# Players with this permission will be able to mine the blocks specified in 'silk_touch_blocks' 
# using a diamond or netherite pickaxe enchanted with Silk Touch.
Silk-Touch-Permission: "customizablesilktouch.use"

Messages:
  No-Permission: "&cYou cannot use this command!"
  Successfully-Reloaded: "&aSuccessfully reloaded configuration!"

Silk-Touch-Tools:
  Default:
    # List of materials that will match this tool set.
    Materials:
      - "DIAMOND_PICKAXE"
      - "NETHERITE_PICKAXE"
    # List of blocks that are affected by the customisable silk touch.
    # Add the desired blocks in ALL_CAPS.
    # The blocks specified here can only be mined with Silk Touch enchantment by the players having 'silk_touch_permission'.
    # Currently, BUDDING_AMETHYST and SPAWNER blocks are affected.
    Silk-Touch-Blocks:
      - "BUDDING_AMETHYST"
      - "SPAWNER"
    # List of blocks that are naturally silk touchable but
    # are now blocked and converted to the right material.
    # Format: SILK_BLOCK:NEW_DROP
    # Examples:
    # - "STONE:COBBLESTONE"
    # - "GOLD_ORE:RAW_GOLD"
    Blocked-Blocks:
      - "STONE:COBBLESTONE"