name: CustomizableSilkTouch
version: '1.9'
main: com.ashkiano.customizablesilktouch.CustomizableSilkTouch
api-version: '1.20'
authors: [ AshKiano, BitByLogic ]
commands:
  customizablesilktouch:
    aliases: [ "cst" ]
